### ISSUE TITLE
bookmark handles unproperly in 0.4.0

### ISSUE THREAD

**Issue by Wongboo** [touying-typ/touying#32]
```
#import "@preview/touying:0.4.0": *

#let s = themes.university.register()
#let (init, slides) = utils.methods(s)
#show: init

#let (slide, empty-slide) = utils.slides(s)
#show: slides

= Section

== Title 1

#slide[
	1
]

== Title 2

#slide[
	2
]

Hello, Touying!
```
has no bookmark, while `0.3.3` has.

**Comment by OrangeX4** [comment]
This is because the original header of the university theme contains heading, but this conflicts with the `set heading(numbering: "1.1")`, so the `heading` is replaced with `text`, and there is no bookmark. Will I consider the need for bookmarks, but the problem at the moment is that it will conflict with numbering.

**Comment by Wongboo** [comment]
Even in `0.3.3`, package will create multiple bookmarks for all pages with the same title, I think the design is weird.
